apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-auth-config
  namespace: longhorn-system
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      server {
        listen 80;
        server_name _;
        
        # Basic auth configuration
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/auth;
        
        # Proxy to Longhorn
        location / {
          proxy_pass http://longhorn-frontend:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-auth-proxy
  namespace: longhorn-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-auth-proxy
  template:
    metadata:
      labels:
        app: nginx-auth-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: auth
          mountPath: /etc/nginx/auth
          subPath: auth
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-auth-config
      - name: auth
        secret:
          secretName: basic-auth
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-auth-proxy
  namespace: longhorn-system
spec:
  selector:
    app: nginx-auth-proxy
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP